using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using Microsoft.Phone.Controls;

namespace Guess
{
    public partial class MainPage : PhoneApplicationPage
    {
        List<GameType> GameTypeList;
        
        // Constructor
        public MainPage()
        {
            InitializeComponent();
            //GameList.ItemsSource = new List<string> {"Go To The Zoo", "Celebrity", "Silence, Please", "Silver Screen", "Turn Up The Radio", "Kid Stuff", "Pictures Please", "Logos", "Foods", "Potpourri" };
        }

        protected override void OnNavigatedTo(System.Windows.Navigation.NavigationEventArgs e)
        {
            BuildGameList();
        }

        private void BuildGameList()
        {
            GameTypeList = new List<GameType>();
            GameTypeList.Add(new GameType { Name = "Go To The Zoo", SortOrder = 1, ImageLocation = "Images/GameType/GoToTheZoo.jpg", Description = "Get your friends to guess the animal on the card without using any part of the animal's name.", Cards = new List<string> { "Panda", "Zebra", "Horse", "Tiger", "Alligator", "Badger", "Bear", "Beaver", "Butterfly", "Camel", "Cat", "Cheetah"} });
            GameTypeList.Add(new GameType { Name = "Fame Game", SortOrder = 2, ImageLocation = "Images/GameType/FameGame.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" }});
            GameTypeList.Add(new GameType { Name = "Sing Me A Song", SortOrder = 3, ImageLocation = "Images/GameType/SingMeASong.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" } });
            GameTypeList.Add(new GameType { Name = "Fame Game", SortOrder = 2, ImageLocation = "Images/GameType/FameGame.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" } });
            GameTypeList.Add(new GameType { Name = "Fame Game", SortOrder = 2, ImageLocation = "Images/GameType/FameGame.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" } });
            GameTypeList.Add(new GameType { Name = "Fame Game", SortOrder = 2, ImageLocation = "Images/GameType/FameGame.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" } });
            GameTypeList.Add(new GameType { Name = "Fame Game", SortOrder = 2, ImageLocation = "Images/GameType/FameGame.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" } });
            GameTypeList.Add(new GameType { Name = "Fame Game", SortOrder = 2, ImageLocation = "Images/GameType/FameGame.jpg", Description = "Get your friends to guess the name of the celebrity on the card without using any part of the person's name.  Rhyming is also cheating.", Cards = new List<string> { "Jennifer Lopez", "Oprah Winfrey", "Justin Bieber", "Rihanna", "Lady Gaga", "Britney Spears", "Kim Kardashian", "Katy Perry", "Tom Cruise", "Steven Spielberg", "Taylor Swift", "Angelina Jolie", "Donald Trump", "Beyonce Knowles", "Elton John", "Simon Cowell", "Paul McCartney", "Jennifer Aniston", "Adele", "Jon Bon Jovi", "Dr. Dre", "Brad Pitt", "Ryan Seacrest", "Howard Stern", "Ellen Degeneres", "George Lucas", "Jay-Z", "David Letterman", "P. Diddy", "Kristen Stewart", "Kanye West", "Leonardo DiCaprio", "Toby Keith", "Ashton Kutcher", "Kenny Chesney", "Sandra Bullock", "Johnny Depp", "Adam Sandler", "Chris Rock", "Will Smith", "Cameron Diaz", "Jerry Seinfeld", "Tom Hanks", "Stephen King", "Taylor Lautner", "Dwayne Johnson", "Ben Stiller", "Jason Bateman", "Seth MacFarlane", "Charlize Theron", "Sofia Vergara", "Alec Baldwin", "Tina Fey", "Julia Roberts", "Maryl Streep", "J.K. Rowling", "Sarah Jessica Parker", "Hugh Laurie", "Zooey Deschanel" } });
            GameList.ItemsSource = GameTypeList;
        }

        private void Game_Tapped(object sender, MouseButtonEventArgs e)
        {
            NavigationService.Navigate(new Uri("/CardPage.xaml", UriKind.Relative));
        }
    }
}